### ISSUE TITLE
Nice one!

### ISSUE THREAD

**Issue by FGRibreau** [sonots/redis_waitlock#1]
Nice one @sonots :)

Your gem will be shared in our next [RedisWeekly](http://redisweekly.com) :)!

**Comment by sonots** [comment]
Glad to hear that ^^

**Comment by sonots** [comment]
Oh, redis_waitlock is the old one, https://github.com/sonots/redis_getlock is currently working one. Could you introduce redis_getlock instead?

**Comment by sonots** [comment]
Let me delete redis_waitlock repository, redis_waitlock gem is not released one.
